### ISSUE TITLE
Add Example Render

### ISSUE THREAD

**Issue by xentripetal** [Antoshidza/NSprites#1]
It would be helpful to have an example implementation of a valid render archetype or shader. I'm unsure how to handle the matrices property in a custom shader.

p.s. I really appreciate you working on this and making it public! Its a very noticeable gap in the DOTS ecosystem

**Comment by Antoshidza** [comment]
Hi @xentripetal!

I'm currently working on huge revision of this system, so there is no documentation here, it is very raw package you can still use though with 0.50 Entities package. You can see future changes in "rework-buffer-management" branch (name doesn't reflect all meaning). For example 2D Transforms / Sorting was removed from package's core and will be provided as separate package or simply through gists.

Still basically the core principles remains the same. Render archetype implementation is really whatever you want to use to keep data you need to pass to `SpriteRenderingSystem`. In my project it is `ScriptableObject` with material/instanced properties names/matrices property name (deprecated) which I then use with `SpriteRenderingSystem.RegistrateRender()`. 

Here is compatible [shader](<script src="https://gist.github.com/Antoshidza/387bf4a3a3efd62c8ca4267e800ad3bc.js"></script>) with this package on main branch. I will update this gist with future updates. The main thing in this shader is `StructuredBuffer<T> _propertyName` which should be registered as instanced property

**Comment by Antoshidza** [comment]
Hi again @xentripetal 

I've done with system rework and finally have written basic documentation. Still it is not render example but it is far simpler to figure out how to work with system.

Though my next step is to provide example project.

**Comment by Antoshidza** [comment]
Hi @xentripetal !

I've finally implemented [sample project](https://github.com/Antoshidza/Age-of-Sprites). There is an example of how to
- register renderers
- prepare data
- culling
- sorting
- animation
