### ISSUE TITLE
use compute shader + bitonic sort to compute sorting order

### ISSUE THREAD

**Issue by yhd4711499** [Antoshidza/NSprites#10]
The rendering performance is impressive but I noticed that computing sort value is slow compared to the rendering.

Maybe the sorting work could be done on GPU and the result could be consumed in sprite shader thus no CPU is involved.

I found this repo https://github.com/hiroakioishi/UnityGPUBitonicSort/tree/master and have a simple performance test:

3 GHz 6 core Intel Core i5
Radeon Pro 570X 4 GB
Unity 2021.3.14
Running in Editor

buffer size: 262144
sorting cost (no ComputeBuffer.GetData): 0.0783 ms

**Comment by Antoshidza** [comment]
NSprites (this repo in particular) has no sorting at all. I believe you [foundation](https://github.com/Antoshidza/NSprites-Foundation) which is more an example rather then production ready solution. Also link which you provide goes nowhere for me
