### ISSUE TITLE
Sprite not rendering when use SpriteAnimatedRendererAuthoring

### ISSUE THREAD

**Issue by Tangkysin** [Antoshidza/NSprites#12]
I'm using 1.016 Entities and Entities Graphics with NSprite 4.0.0 and NSprite Foundation 6.0.3

![WX20240227-150653](https://github.com/Antoshidza/NSprites/assets/5828255/8c7a4eb4-a188-4dd9-8000-79ac1d473655)

SImply add one GameObject to the subscene and add SpriteAnimatedRendererAuthoring with those Animation from Age-of-Sprites Project,  the Sprite Frame Animation dosen't show as expected neither editor mode nor runtime mode 

![WX20240227-150726](https://github.com/Antoshidza/NSprites/assets/5828255/3e61a2e1-3f08-4e75-b31e-2263aa771a28)

**Comment by Tangkysin** [comment]
framedebuger shows no player rendering frame exist，but animation switch correct

**Comment by Tangkysin** [comment]
it suppose a little soldier under the write cirle
![WX20240227-151555](https://github.com/Antoshidza/NSprites/assets/5828255/e71595f6-b741-4cda-a77c-352b2b6d9c2a)

**Comment by Antoshidza** [comment]
1. Have you checked [troubleshooting](https://discord.com/channels/1130772288430682174/1172485643717333022/1172485643717333022) post on discord server?
2. Do your's tower and white circle rendered with NSprites or is it just `SpriteRenderer` on gameobject?
3. Do you use sorting? I see that you choose custom sorting layer `TownEntity`. Can it be that solider is under ground?

**Comment by Tangkysin** [comment]
> 1. Have you checked [troubleshooting](https://discord.com/channels/1130772288430682174/1172485643717333022/1172485643717333022) post on discord server?
> 2. Do your's tower and white circle rendered with NSprites or is it just `SpriteRenderer` on gameobject?
> 3. Do you use sorting? I see that you choose custom sorting layer `TownEntity`. Can it be that solider is under ground?

fix it，it the shader problem，it was a 2D peoject，thanks
