### ISSUE TITLE
Will be Supprot Material Properity animation and Transform animtion in ther feature

### ISSUE THREAD

**Issue by liyou54** [Antoshidza/NSprites#19]

**Comment by Antoshidza** [comment]
There can be any type of material properties and any way to animate them (same for transform). I don't want to stick this package with any particular approach. This package has one responsibility: render sprites (or any mesh if you want) it also has some essentials for working with sprites in particular but they are few. 
NSprites-Foundation is more detailed about sprites it provides some example system to working with sprites but still don't want to insist on any concrete approach.
So if you need to animate some material parameter or transform do it in your systems or you can use some community animation packages if they can be used with NSprites entities.
